2023년 봄학기 세미나 1 (블로그 글)
bacchus-snu/bacchus-homepage pull request #31
Opened 2023-06-10 07:34 UTC by nick11967

5월 18일에 진행했던 봄학기 세미나에 대한 블로그 글입니다.
몇 가지 피드백 받고 싶은 내용이 있습니다.
사진을 넣으려고 하는데 레포 내에서 어떻게 관리하는 것이 좋을지 의견 부탁드립니다.
위쪽 'date' 부분에 세미나를 진행한 날짜를 넣을지 작성한 날짜를 넣을지 고민 중입니다.
처음으로 작성한 글이라서 피드백 주시면 반영할 수 있도록 해보겠습니다.

@vegadodo 리뷰 부탁드립니다!
@skystar-p @pbzweihander @nevivurn 발표자 분들도 한 번씩 봐주시면 좋을 것 같습니다.

2023-06-10 09:58 UTC, vegadodo requested changes
전반적인 내용은 좋은 것 같습니다! 몇 가지 사소하게 수정할 만한 부분에 대해 코멘트 남겼습니다.

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
- 어투 통일
  - `발표였다` -> `발표였습니다`
- 고유명사 표기
  - `하스켈` -> `Haskell`
- 문장 호응
  - `이번 발표에는` -> `이번 발표에서는`
  - `얻을 수` -> `배울 수`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +date: 2023-05-18
ISO 8601 is the best standard 👍

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +두번째 발표는, 이강욱님의 <Introduction to Game Server Development>였습니다. 발표자는 이전 Spoqa에서 풀스택 프로그래머를 근무한 적이 있으며, 현재 Devsisters에서 DevOps Engineer로 근무하고 계십니다.
- 문장 호응
  - `풀스택 프로그래머를` -> `풀스택 프로그래머로`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +그 경력을 살려 이번 발표에서는 게임 서버에 개발에 대해서 마중물 역할을 해줄 수 있는 키워드들을 제공해주셨습니다.
- 문장 호응
  - `게임 서버에 개발에 대해서` > `게임 서버 개발에 있어서`
  - `제공` -> `제시`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +그 이후에는 비 실시간 게임 서버에 대해서 잠시 언급하고, 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 kubernetes와 agones를 말씀해주셨고, 각각에 대한 설명이 있었습니다.
- 고유명사 표기
  - `kubernetes` -> `Kubernetes`
  - `agones` -> `Agones`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +세번째 발표는, 성용운님의 NIXOS에 대한 발표였습니다. Linux의 대표 배포판인 debian, ubuntu와는 다르게 NIXOS는 자체적으로 제공하는 기본 설정파일 하나만으로 쉽게 서버를 올릴 수 있는 장점이 있음을 설명해주셨습니다. 그에 대한 데모로 마인크래프트 서버를 NIXOS에서 어떻게 올릴 수 있는지 시연을 하셨다. NIXOS는 빌드시에 캐시
- 고유명사 표기
  - `NIXOS` -> `NixOS`
  - `debian` -> `Debian`
  - `ubuntu` -> `Ubuntu`
- 어투 통일
  - `시연을 하셨다` -> `시연을 하셨습니다`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> + - 데브시스터즈에서 어떤 언어를 사용하는지에 대한 질문이 있었습니다. 이에 대하여 Go, Scalar 등을 사용한다는 답변이
- 고유명사 표기
  - `Scalar` -> `Scala`
- 문장 호응
  - `사용한다는 답변이` -> `사용한다고 답변하셨습니다.`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> + - 데브시스터즈는 게임서버 개발을 어떻게 하고 있나라는 질문이 있었습니다. infra팀과 게임개발자와 분리되어 있어서, infra팀에서 게임 개발자들에게 서버를 쉽게 만들 수 있게 api를 제공해준다고 했다.
- 문장 호응
  - `게임개발자와 분리되어` -> `게임개발자가 분리되어`
- 어투 통일
  - `제공해준다고 했다` -> `제공해준다고 했습니다`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +그 일환으로 6월 말에 세미나를 추가 진행하기로 하였습니다. 기술에 대해 많이 몰라도 즐길 수 있는 키보드 배열에 대해 발표, 가계부를 어떻게 써야하는지 발표 등이 예정되어 있습니다.
- 문장 호응
  - `배열에 대해` -> `배열에 대한`
  - `써야하는지 발표` -> `써야하는지에 대한 발표`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> +코로나 중에서도 지속적으로 열렸지만, 이번 세미나는 코로나 이후 처음으로 열리는 세미나라 많은 기대를 품고 다들 모여주셨습니다.
- 문장 호응
  - `중에서도 지속적으로` -> `중에도 세미나는 지속적으로`
  - `많은 기대를 품고 다들` -> `다들 많은 기대를 품고`

2023-06-10 09:58 UTC, vegadodo commented on source/_posts/etc/20230518seminar.md
> + - (대충 하스켈 Q&A concurrency) Q1: concurrancy가 붙으면? A1: 가변성이 있어도 타입 레벨에서 분리가 된다
- 오타
  - `concurrancy` -> `concurrency`

2023-06-10 13:54 UTC, pbzweihander requested changes

2023-06-10 13:54 UTC, pbzweihander commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
`박재현님` -> `박재현 님` 이 맞습니다. 같은 리뷰는 생략할게요

2023-06-10 13:54 UTC, pbzweihander commented on source/_posts/etc/20230518seminar.md
> +그 이후에는 비 실시간 게임 서버에 대해서 잠시 언급하고, 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 kubernetes와 agones를 말씀해주셨고, 각각에 대한 설명이 있었습니다.
어떤 언급이 있었는지 있었으면 좋겠다? optional입니다. container 이야기 했다 정도 적으면 좋지 않을까요

2023-06-13 02:41 UTC, skystar-p commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
쿠키런 서버 엔지니어는 이전 업무라서 이전 / 현재로 표기해주시면 감사하겠습니다...!

2023-06-13 02:41 UTC, skystar-p commented on source/_posts/etc/20230518seminar.md
> + - (대충 하스켈 Q&A concurrency) Q1: concurrancy가 붙으면? A1: 가변성이 있어도 타입 레벨에서 분리가 된다
아마 이 부분이 제가 기억하기로는 "가변성이 있는 자료구조가 있다면 하스켈의 Concurrency 구현에서 Race condition이 발생할 위험이 있지 않은가?" 라는 질문이었던 것 같은데... "가변 타입과 동시성 자료 타입이 구분되어 있어 문제 없을 것" 이라고 답변했던 것 같아요

2023-06-17 08:37 UTC, sailor1493 commented
활발한 리뷰 감사합니다 :)

2023-06-22 05:08 UTC, nick11967 commented
수정이 좀 늦어졌습니다. 죄송합니다. 피드백 반영하여 수정하였습니다! 한 번 더 피드백 받고 merge 하도록 하겠습니다.
전체적으로 표현 같은 것을 통일하는데 집중하여 고쳐봤습니다. 이미지도 추가했습니다. 이미지 추가할 때 경로에 대한 말이 없어서 임의로 `_posts/` 아래에 `images/` 만들어서 추가하였습니다.  
이번에 반영된 주요 피드백들 포함하여 홈페이지 글쓰기 howto에 아래 내용을 추가할까 합니다. 이거는 가을 학기에 신입 모집하면서 블로그 글을 한 번 더 작성하게 된다면 그 이후에 추가하는 것이 좋을 것 같습니다. 글 형식 같은 것은 한 번 더 써보고 정하면 좋을 것 같아서요.
+ 이미지 추가하는 방법(경로)
+ 반드시 들어갈 내용 (작성자 등)

2023-06-22 12:10 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +코로나 중에서도 지속적으로 열렸지만, 이번 세미나는 코로나 이후 처음으로 열리는 세미나라 많은 기대를 품고 다들 모여주셨습니다.
반영됐더라구요

2023-06-22 12:21 UTC, sailor1493 reviewed
사소한 부분 수정 suggestion 넣었습니다. apply 후 멘션 해주시면 approve해둘게요.

2023-06-22 12:21 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +#### 하스켈 한 스푼 (박재현)
Haskell로 통일
```suggestion
#### Haskell 한 스푼 (박재현)
```

2023-06-22 12:21 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +첫 번째 발표는 박재현 님의 Haskell에 대한 발표였습니다. 박재현 님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 이전에 Devsisters에서 쿠키런 서버 엔지니어로 근무하셨고 현재 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 Haskell이라는 언어를 공부하시고 느낀 특징들을 중심으로 발표해 주셨습니다. Haskell은 함
놓친 Haskell 등...
```suggestion
첫 번째 발표는 박재현 님의 Haskell에 대한 발표였습니다. 박재현 님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 이전에 Devsisters에서 쿠키런 서버 엔지니어로 근무하셨고 현재 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에서는 Haskell이라는 언어를 공부하시고 느낀 특징들을 중심으로 발표해 주셨습니다. Haskell은 함수형 프로그래밍 언어입니다. Haskell은 세가지 특징(불변성, 통제된 가변성, 강력한 동시성)을 가지고 있다고 설명해 주셨습니다. 이런 장점들이 있어 충분히 사용할 만하지만 단점도 있습니다. 대표적인 단점으로 Laziness, Char 배열로 구현되는 String, 툴링에서의 아쉬움 등을 제시해 주셨습니다. 이런 것들을 공부하면서, Haskell의 장점 덕분에 흥미로웠으나 몇몇 단점들 때문에 사용하기 힘들다는 의견을 주셨습니다. Haskell에 대한 전반적인 개념과 느낌을 배울 수 있는 발표였습니다.
```

2023-06-22 12:21 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +그 이후에는 비 실시간 게임 서버와 관련하여 containuer를 사용할 수 있음을 이야기 해 주셨습니다. 다음으로 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 Kubernetes와 Agones를 말씀해 주셨고, 각각에 대한 설명이 있었습니다.
오타 수정
```suggestion
그 이후에는 비 실시간 게임 서버와 관련하여 container를 사용할 수 있음을 이야기 해 주셨습니다. 다음으로 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 Kubernetes와 Agones를 말씀해 주셨고, 각각에 대한 설명이 있었습니다. 
```

2023-06-22 12:21 UTC, sailor1493 reviewed
사소한 부분 수정 suggestion 넣었습니다. apply 후 멘션 해주시면 approve해둘게요.

2023-06-22 12:22 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
요건 반영되었습니다

2023-06-22 12:23 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +그 이후에는 비 실시간 게임 서버에 대해서 잠시 언급하고, 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 kubernetes와 agones를 말씀해주셨고, 각각에 대한 설명이 있었습니다.
언급했습니다.

2023-06-22 14:11 UTC, nick11967 commented on source/_posts/etc/20230518seminar.md
> +#### 하스켈 한 스푼 (박재현)
이건 발표자료 제목을 그대로 가져온거라 수정하지 않으려고 합니다.

2023-06-22 14:13 UTC, nick11967 commented
@sailor1493 approve 부탁드립니다!

2023-06-22 14:16 UTC, sailor1493 approved these changes

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
checked

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +그 일환으로 6월 말에 세미나를 추가 진행하기로 하였습니다. 기술에 대해 많이 몰라도 즐길 수 있는 키보드 배열에 대해 발표, 가계부를 어떻게 써야하는지 발표 등이 예정되어 있습니다.
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> + - 데브시스터즈는 게임서버 개발을 어떻게 하고 있나라는 질문이 있었습니다. infra팀과 게임개발자와 분리되어 있어서, infra팀에서 게임 개발자들에게 서버를 쉽게 만들 수 있게 api를 제공해준다고 했다.
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> + - 데브시스터즈에서 어떤 언어를 사용하는지에 대한 질문이 있었습니다. 이에 대하여 Go, Scalar 등을 사용한다는 답변이
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +그 이후에는 비 실시간 게임 서버에 대해서 잠시 언급하고, 실시간 게임 서버를 어떻게 배포하는지 설명하셨습니다. 그 방법으로 kubernetes와 agones를 말씀해주셨고, 각각에 대한 설명이 있었습니다.
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +그 경력을 살려 이번 발표에서는 게임 서버에 개발에 대해서 마중물 역할을 해줄 수 있는 키워드들을 제공해주셨습니다.
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +두번째 발표는, 이강욱님의 <Introduction to Game Server Development>였습니다. 발표자는 이전 Spoqa에서 풀스택 프로그래머를 근무한 적이 있으며, 현재 Devsisters에서 DevOps Engineer로 근무하고 계십니다.
반영되었습니다.

2023-06-22 14:16 UTC, sailor1493 commented on source/_posts/etc/20230518seminar.md
> +첫번째 발표는, 박재현님의 하스켈에 관한 발표였다. 박재현님은 바쿠스에서 대표 및 부대표를 한 적이 있으시며, 현재 Devsisters에서 쿠키런 서버 엔지니어및 인프라팀 DevOps 엔지니어로 근무중이십니다. 이번 발표에는 하스켈이라는 언어를 공부하시고 하스켈의 특징들을 중심으로 발표해주셨습니다. 하스켈은 함수형 프로그래밍 언어입니다. 하스켈은 세가지
반영되었습니다.

2023-06-22 14:40 UTC, merged